
# pylint: disable=invalid-name,too-few-public-methods

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800

FIELD_WIDTH = 1820
FIELD_HEIGHT = 2430
FIELD_BOUNDARY_GAP = 250
FIELD_LINE_WIDTH = 50

WALL_WIDTH = 10

ROBOT_WIDTH = 15
ROBOT_SPEED = 5

LIDAR_RENDER_LENGTH = 30
LIDAR_PING_RADIUS = 5
LIDAR_RPS = 10
LIDAR_RES = 0.9


FIELD_WIDTH = 1820
FIELD_HEIGHT = 2430
WALL_WIDTH = 50
FIELD_MARGIN = 20
FIELD_SCALE = max((FIELD_WIDTH + WALL_WIDTH * 2 + FIELD_MARGIN * 2) / SCREEN_WIDTH,
                  (FIELD_HEIGHT + WALL_WIDTH * 2 + FIELD_MARGIN * 2) / SCREEN_HEIGHT)


class ROBOT:
    RADIUS = int(100 / FIELD_SCALE)


class FIELD:
    WIDTH = int(FIELD_WIDTH / FIELD_SCALE)
    HEIGHT = int(FIELD_HEIGHT / FIELD_SCALE)
    BOUNDARY_GAP = int(300 / FIELD_SCALE)
    LINE_WIDTH = int(20 / FIELD_SCALE)
    GOAL_WIDTH = int(600 / FIELD_SCALE)
    GOAL_DEPTH = int(74 / FIELD_SCALE)
    BOX_WIDTH = int(900 / FIELD_SCALE)
    BOX_DEPTH = int(300 / FIELD_SCALE)
    CENTER_POINT_GAP = int(300 / FIELD_SCALE)
    WALL_WIDTH = int(WALL_WIDTH / FIELD_SCALE)


class COLORS:
    BLACK = (0, 0, 0)
    WHITE = (255, 255, 255)
    BLUE = (0, 0, 255)
    GREEN = (0, 255, 0)
    RED = (255, 0, 0)
    GRAY = (128, 128, 128)


# pylint: enable=invalid-name,too-few-public-methods
